[package]
name = "rktop"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.28"
crossterm = "0.28"
sysinfo = "0.32"
regex = "1.11"
anyhow = "1.0"
thiserror = "2.0"
nix = { version = "0.29", features = ["user"] }
goblin = "0.9"
